export const colors = {
  accent: 'var(--color-accent)',
  'accent-hover': 'var(--color-accent-hover)',
  'accent-muted': 'var(--color-accent-muted)',
  'accent-subtle': 'var(--color-accent-subtle)',

  'bg-base': 'var(--color-bg-base)',
  'bg-inset': 'var(--color-bg-inset)',
  'bg-secondary': 'var(--color-bg-secondary)',
  'bg-surface': 'var(--color-bg-surface)',
  'bg-surface-hover': 'var(--color-bg-surface-hover)',
  'bg-elevated': 'var(--color-bg-elevated)',
  'bg-overlay': 'var(--color-bg-overlay)',
  'bg-input': 'var(--color-bg-input)',
  'bg-header': 'var(--color-bg-header)',

  'text-primary': 'var(--color-text-primary)',
  'text-secondary': 'var(--color-text-secondary)',
  'text-tertiary': 'var(--color-text-tertiary)',
  'text-disabled': 'var(--color-text-disabled)',
  'text-inverse': 'var(--color-text-inverse)',

  'border-default': 'var(--color-border-default)',
  'border-subtle': 'var(--color-border-subtle)',
  'border-strong': 'var(--color-border-strong)',
  'border-focus': 'var(--color-border-focus)',

  'status-success': 'var(--color-status-success)',
  'status-success-bg': 'var(--color-status-success-bg)',
  'status-warning': 'var(--color-status-warning)',
  'status-warning-bg': 'var(--color-status-warning-bg)',
  'status-error': 'var(--color-status-error)',
  'status-error-bg': 'var(--color-status-error-bg)',
  'status-info': 'var(--color-status-info)',
  'status-info-bg': 'var(--color-status-info-bg)',
  'status-offline': 'var(--color-status-offline)',
  'status-offline-bg': 'var(--color-status-offline-bg)',
  'status-warning-hover': 'var(--color-status-warning-hover)',

  'method-get': 'var(--color-method-get)',
  'method-post': 'var(--color-method-post)',
  'method-put': 'var(--color-method-put)',
  'method-delete': 'var(--color-method-delete)',

  'syntax-string': 'var(--color-syntax-string)',
  'syntax-number': 'var(--color-syntax-number)',
  'syntax-boolean': 'var(--color-syntax-boolean)',
  'syntax-null': 'var(--color-syntax-null)',
  'syntax-key': 'var(--color-syntax-key)',
  'syntax-function': 'var(--color-syntax-function)',
  'syntax-symbol': 'var(--color-syntax-symbol)',
  'syntax-bracket': 'var(--color-syntax-bracket)',

  recording: 'var(--color-recording)',
} as const;

export const colorValues = {
  accent: '#6C6CFF',
  'accent-hover': '#8585FF',
  'accent-muted': '#4A4AFF',
  'accent-subtle': '#6C6CFF1A',

  'bg-base': '#0F0F1E',
  'bg-inset': '#0B0B18',
  'bg-secondary': '#141428',
  'bg-surface': '#1A1A32',
  'bg-surface-hover': '#222244',
  'bg-elevated': '#2A2A4A',
  'bg-overlay': '#32325A',
  'bg-input': '#0C0C1A',
  'bg-header': '#0A0A16',

  'text-primary': '#E8E8F0',
  'text-secondary': '#9898B0',
  'text-tertiary': '#686888',
  'text-disabled': '#484868',
  'text-inverse': '#FFFFFF',

  'border-default': '#2A2A48',
  'border-subtle': '#1E1E3A',
  'border-strong': '#3A3A5C',
  'border-focus': '#6C6CFF',

  'status-success': '#4ADE80',
  'status-success-bg': '#0D2818',
  'status-warning': '#FBBF24',
  'status-warning-bg': '#1E1800',
  'status-error': '#F87171',
  'status-error-bg': '#1E0808',
  'status-info': '#60A5FA',
  'status-info-bg': '#0F1A2D',
  'status-offline': '#737373',
  'status-offline-bg': '#1A1A1A',
  'status-warning-hover': '#FCD34D',

  'method-get': '#60A5FA',
  'method-post': '#4ADE80',
  'method-put': '#FBBF24',
  'method-delete': '#F87171',

  'syntax-string': '#a6e3a1',
  'syntax-number': '#89b4fa',
  'syntax-boolean': '#cba6f7',
  'syntax-null': '#585b70',
  'syntax-key': '#cdd6f4',
  'syntax-function': '#fab387',
  'syntax-symbol': '#94e2d5',
  'syntax-bracket': '#6c7086',

  recording: '#EF4444',
} as const;
